-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgW46s7G5PPV52j2F/
JJNj5wOQcvOeZMogPSmxNiJut6OgCgYIKoZIzj0DAQehRANCAATlccE8gnE2XDBR
Ol33g4q5jErUMwHBxlVRsJhHRic4Y4KWLDv2yf+t/c+7S/oNYmQahQHIOYid5rci
HCLXD+BX
-----END PRIVATE KEY-----